### ISSUE TITLE
exceptionify not working

### ISSUE THREAD

**Issue by marijn** [schmittjoh/JMSCommandBundle#10]
When I run `$ bin/dev exceptionify MyBundle` I get no errors. However, no classes were generated by the command. 

My version: `Symfony version 2.1.0-DEV - app/dev/debug`

I'll try to look into it more detailed after the weekend. Any suggestions?

**Comment by schmittjoh** [comment]
Do you use exceptions in your bundle? :)

**Comment by marijn** [comment]
That's some proper architecture right there! I hope to pad you on the shoulder for this one next week :smile:
